# Reincarceration Configuration

# Economy settings
economy:
  entry-fee: 125000
  random-modifier-discount: 0.5
  rank-up-costs:
    - 15000
    - 35000
    - 65000
    - 100000

start_location: # This was meant to just send them to the prison but suffocating them at the location also works
  world: "world"
  x: 233
  y: 67
  z: -82

# Rank settings
ranks:
  0:
    name: "C✪"
    permission-group: "reoffender_c"
  1:
    name: "B✪"
    permission-group: "reoffender_b"
  2:
    name: "A✪"
    permission-group: "reoffender_a"
  3:
    name: "Elite✪"
    permission-group: "reoffender_elite"

# Database settings
database:
  filename: "reincarceration_data.db"

reoffender-vault-number: 15

# Permission settings
permissions:
  entry-group: "citizen"  # The group players are in when not in a cycle
  base-group: "reoffender" # The base group for all reoffenders

# Plugin messaging
prefix: "&8[&6Reincarceration&8] &r"  # Prefix for all plugin messages

# Debug mode (set to true for additional logging)
debug-mode: false

item_flagging:
  use_whitelist: false  # If true, use whitelist; if false, use blacklist
  whitelist:
    - DIAMOND
    - IRON_INGOT
    - GOLD_INGOT
  blacklist:
    - BEDROCK
    - COMMAND_BLOCK
    - BARRIER
    - SHULKER_BOX
    - WHITE_SHULKER_BOX
    - ORANGE_SHULKER_BOX
    - MAGENTA_SHULKER_BOX
    - LIGHT_BLUE_SHULKER_BOX
    - YELLOW_SHULKER_BOX
    - LIME_SHULKER_BOX
    - PINK_SHULKER_BOX
    - GRAY_SHULKER_BOX
    - LIGHT_GRAY_SHULKER_BOX
    - CYAN_SHULKER_BOX
    - PURPLE_SHULKER_BOX
    - BLUE_SHULKER_BOX
    - BROWN_SHULKER_BOX
    - GREEN_SHULKER_BOX
    - RED_SHULKER_BOX
    - BLACK_SHULKER_BOX
    - DIAMOND_BLOCK
    - GOLD_BLOCK
    - IRON_BLOCK
    - EMERALD_BLOCK
    - LAPIS_BLOCK
    - NETHERITE_BLOCK
    - COAL_BLOCK
    - REDSTONE_BLOCK
    - COPPER_BLOCK
    - WATER_BUCKET
    - OBSIDIAN
    - LAVA_BUCKET
    - ELYTRA

block_blacklist:
  blocks:
    - BEDROCK
    - COMMAND_BLOCK
    - BARRIER
    - SHULKER_BOX
    - WHITE_SHULKER_BOX
    - ORANGE_SHULKER_BOX
    - MAGENTA_SHULKER_BOX
    - LIGHT_BLUE_SHULKER_BOX
    - YELLOW_SHULKER_BOX
    - LIME_SHULKER_BOX
    - PINK_SHULKER_BOX
    - GRAY_SHULKER_BOX
    - LIGHT_GRAY_SHULKER_BOX
    - CYAN_SHULKER_BOX
    - PURPLE_SHULKER_BOX
    - BLUE_SHULKER_BOX
    - BROWN_SHULKER_BOX
    - GREEN_SHULKER_BOX
    - RED_SHULKER_BOX
    - BLACK_SHULKER_BOX
    - DIAMOND_BLOCK
    - GOLD_BLOCK
    - IRON_BLOCK
    - EMERALD_BLOCK
    - LAPIS_BLOCK
    - NETHERITE_BLOCK
    - COAL_BLOCK
    - REDSTONE_BLOCK
    - COPPER_BLOCK
    - OBSIDIAN

blacklisted_containers:
  - ENDER_CHEST
  - SHULKER_BOX
  - BARREL
  - TRAPPED_CHEST
allowed_container_title_patterns:
  - "me.gypopo.economyshopgui.objects.TransactionMenu"
#  - "Buying"
#  - "Market"

# Modifier settings
modifiers:
  ore_sickness:
    effect_on_break: true
    effect_on_sight: true
    effect_duration: 200
    sight_check_radius: 5
    line_of_sight_step: 0.1
    field_of_view: 80
    check_frequency: 20
    ore_effects:
      COAL_ORE:
        type: collapse
        allowed_blocks:
          - STONE
          - DIRT
          - SANDSTONE
          - NETHERRACK
          - NETHER_BRICKS
          - RED_NETHER_BRICKS
          - SNOW
        affected_radius: 4

      DEEPSLATE_COAL_ORE:
        type: potion
        effect: WITHER
        duration: 200
        amplifier: 1

      COPPER_ORE:
        type: hunger
        amount: 2

      DEEPSLATE_COPPER_ORE:
        type: potion
        effect: CONFUSION
        duration: 200
        amplifier: 1

      IRON_ORE:
        type: potion
        effect: SLOW
        duration: 200
        amplifier: 1

      DEEPSLATE_IRON_ORE:
        type: inventory_weight
        duration: 200

      GOLD_ORE:
        type: potion
        effect: POISON
        duration: 200
        amplifier: 1

      DEEPSLATE_GOLD_ORE:
        type: potion
        effect: POISON
        duration: 100
        amplifier: 2

      DIAMOND_ORE:
        type: player_repulsion
        force: 3.0 # I think this level makes things fun

      DEEPSLATE_DIAMOND_ORE:
        type: item_repulsion # probably needs some work but concept is making it repel dropped items
        radius: 5.0
        force: 0.2
        duration: 100

      REDSTONE_ORE:
        type: fire
        duration: 100

      DEEPSLATE_REDSTONE_ORE:
        type: sinking
        allowed_blocks:
          - STONE
          - DIRT
          - SANDSTONE
          - NETHERRACK
          - SNOW
          - NETHER_BRICKS
          - RED_NETHER_BRICKS
        duration: 40
        sink_rate: 0.01

      NETHER_GOLD_ORE:
        type: sound
        sound: BLOCK_ANVIL_PLACE
        volume: 1.0
        pitch: 1.0

      ANCIENT_DEBRIS:
        type: avoidance
        allowed_blocks:
          - STONE
          - DIRT
          - SANDSTONE
          - NETHERRACK
          - SNOW
          - NETHER_BRICKS
          - RED_NETHER_BRICKS
        move_period: 5

      LAPIS_ORE:
        type: inventory_shuffle

      SLIME_BLOCK:
        type: bouncy_blocks
        radius: 1
        duration: 200

      EMERALD_ORE:
        type: block_transform
        from_material: EMERALD_ORE
        to_material: STONE
        radius: 3
    rewards:
      items:
        DIAMOND_PICKAXE:
          name: "&9Strangely Fortuitous Pickaxe"
          enchantments:
            FORTUNE:
              level: 4
            UNBREAKING:
              level: 3
          lore:
            - "&dThis pickaxe was found at the end of a double rainbow."
            - "&6What does it mean?"
  immolation:
    enabled: true
    check_interval: 100
    fire_duration: 200
    spread_fire_duration: 100
    spread_radius: 4.0
    spread_fire_enabled: true
    immolation_chance: 0.1
    boots:
      durability: 1
      repair_cost: 30
      fire_protection_level: 2
    rewards:
      items:
        NETHERITE_HELMET:
          name: "&6F&ci&6r&ce&6f&ci&6g&ch&6e&cr&6'&cs &6H&ce&6l&cm&6e&ct"
          enchantments:
            FIRE_PROTECTION:
              level: 5
            PROTECTION:
              level: 4
            UNBREAKING:
              level: 3
        NETHERITE_CHESTPLATE:
          name: "&6F&ci&6r&ce&6f&ci&6g&ch&6e&cr&6'&cs &6C&ch&6e&cs&6t&cp&6l&ca&6t&ce"
          enchantments:
            FIRE_PROTECTION:
              level: 5
            PROTECTION:
              level: 4
            UNBREAKING:
              level: 3
        NETHERITE_LEGGINGS:
          name: "&6F&ci&6r&ce&6f&ci&6g&ch&6e&cr&6'&cs &cL&6e&cg&6g&ci&6n&cg&6s"
          enchantments:
            FIRE_PROTECTION:
              level: 5
            PROTECTION:
              level: 4
            UNBREAKING:
              level: 3
        NETHERITE_BOOTS:
          name: "&6F&ci&6r&ce&6f&ci&6g&ch&6e&cr&6'&cs &6B&co&6o&ct&6s"
          enchantments:
            FIRE_PROTECTION:
              level: 5
            PROTECTION:
              level: 4
            UNBREAKING:
              level: 3
  neolithic:
    enabled: true
    allowed_tools:
      - WOODEN_PICKAXE
      - STONE_PICKAXE
      - WOODEN_AXE
      - STONE_AXE
      - WOODEN_SHOVEL
      - STONE_SHOVEL
      - WOODEN_HOE
      - STONE_HOE
      - WOODEN_SWORD
      - STONE_SWORD
    rewards:
      items:
        WOODEN_SWORD:
          name: "&6Wooden-Epoxy Sword"
          enchantments:
            SHARPNESS:
              level: 6
            UNBREAKING:
              level: 4
            LOOTING:
              level: 3
            FIRE_ASPECT:
              level: 2
          lore:
            - "&cA wooden sword enhanced with some nanotechnology."
        WOODEN_SHOVEL:
          name: "&6Wooden-Epoxy Shovel"
          enchantments:
            EFFICIENCY:
              level: 7
            UNBREAKING:
              level: 4
          lore:
            - "&cA wooden shovel enhanced with some nanotechnology."
        WOODEN_AXE:
          name: "&6Wooden-Epoxy Axe"
          enchantments:
            EFFICIENCY:
              level: 7
            UNBREAKING:
              level: 4
          lore:
            - "&cA wooden axe enhanced with some nanotechnology."
        WOODEN_HOE:
          name: "&6Wooden-Epoxy Hoe"
          enchantments:
            FORTUNE:
              level: 4
            UNBREAKING:
              level: 4
          lore:
            - "&cA wooden hoe enhanced with some nanotechnology."
        WOODEN_PICKAXE:
          name: "&6Wooden-Epoxy Pickaxe"
          enchantments:
            EFFICIENCY:
              level: 7
            UNBREAKING:
              level: 4
            FORTUNE:
              level: 4
          lore:
            - "&cA wooden pickaxe enhanced with some nanotechnology."
  hardcore:
    enabled: true
    rewards:
      commands_desc:
        - "1x T1, T2, T3 Precious Stone Slot"
        - "1x Inventory Shulker Slot"
      items:
        TOTEM_OF_UNDYING:
          amount: 2
        NETHERITE_SWORD:
          name: "&6Strongman's Sword"
          enchantments:
            SHARPNESS:
              level: 5
            UNBREAKING:
              level: 3
            LOOTING:
              level: 3
            MENDING:
              level: 1
            FIRE_ASPECT:
              level: 2
          lore:
            - "&cA strong sword for a strong man."
  decrepit:
    enabled: true
    max_hearts: 1
    rewards:
      commands_desc:
        - "1x T1, T2, T3 Precious Stone Slot"
        - "1x Inventory Shulker Slot"
      items:
        NETHERITE_SWORD:
          name: "&6Strongman's Sword"
          enchantments:
            SHARPNESS:
              level: 5
            UNBREAKING:
              level: 3
            LOOTING:
              level: 3
            MENDING:
              level: 1
            FIRE_ASPECT:
              level: 2
          lore:
            - "&cA strong sword for a strong man."
  tortoise:
    enabled: true
    slowness_level: 3           # Level of the slowness effect (1 for Slowness I, 2 for Slowness II, etc.)
    resistance_level: 2         # Level of the resistance effect (1 for Resistance I, 2 for Resistance II, etc.)
    mining_haste_level: 1       # Level of the mining haste effect (1 for Haste I, 2 for Haste II, etc.)
    immobilization_duration: 5  # Duration in seconds that the player is immobilized after taking damage
    rewards:
      commands_desc:
        - "Coming Soon: Firework Rocket Of Infinity"
      items:
        ELYTRA:
          name: "&6The Rabbit's Wings"
          enchantments:
            UNBREAKING:
              level: 3
          lore:
            - "&cYou won the race!"
            - "&cWhere did the rabbit get these, anyway?"
  angler:
    enabled: true
    provide_rod_on_death: true
    prevent_rod_durability_loss: true
    push_force: 0.5
    push_interval: 5
    min_water_size: 50
    squid_speed: 0.5
    fishing_pull_force: 0.05
    fishing_pull_duration: 20
    safeguard_threshold: 5
    safeguard_upward_force: 1.0
    safeguard_horizontal_force: 1.5
    min_squid_spawn_distance: 8.0
    max_squid_spawn_distance: 15.0
    allowed_items:
      - COD
      - SALMON
      - TROPICAL_FISH
      - PUFFERFISH
      - NAUTILUS_SHELL
      - FISHING_ROD
      - ENCHANTED_BOOK
      - BOW
      - LILY_PAD
      - BOWL
      - LEATHER
      - LEATHER_BOOTS
      - SADDLE
      - NAME_TAG
      - TRIPWIRE_HOOK
      - STICK
      - INK_SAC
      - BAMBOO
    disallowed_swap_items:
      - COD 60
      - SALMON 25
      - TROPICAL_FISH 2
      - PUFFERFISH 13
    rewards:
      items:
        FISHING_ROD:
          name: "&bBass' Nectar"
          enchantments:
            LURE:
              level: 4
            LUCK_OF_THE_SEA:
              level: 4
            UNBREAKING:
              level: 3
          lore:
            - "&d Why is it pulsing?"
  compact:
    enabled: true
    allowed_inventory_slots: 9
    allowed_hotbar_slots: 9
    rewards:
      commands_desc:
        - "1x Inventory Shulker Slot"
  lumberjack:
    enabled: true
    provide_axe_on_death: false
    special:
      enabled: true
      wolf_pack_chance: 0.05
      wolf_pack_size_min: 1
      wolf_pack_size_max: 6
    allowed_items:
      - BIRCH_LOG
      - BIRCH_PLANKS
      - BIRCH_SAPLING
    rewards:
      items:
        NETHERITE_AXE:
          name: "&6Draven's Axe"
          enchantments:
            SHARPNESS:
              level: 6
            EFFICIENCY:
              level: 6
            UNBREAKING:
              level: 3
          lore:
            - "&4There's some blood on this thing..."
  gambler:
    enabled: false